create_random_files: avoid warning for missing header
create_random_files.c:46:8: warning: implicit declaration of function 'chdir'; did you mean 'mkdir'? [-Wimplicit-function-declaration]

Signed-off-by: Kinglong Mee <kinglongmee@gmail.com>